swagger: '2.0'
info:
  title: Bank Argent API documentation for transactions 
  description: Contains all available API endpoints to handle user's transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: List of all Transactions
      description: API for fetching all user's transactions
      parameters:
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: loading of all transactions 
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transactions/detailedView/transaction{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Detailed View
      summary: Detailed View of a transaction in a new view 
      description: API for fetching one user's transaction and all its informations and notes
      parameters:
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: integer
          name: id
          description: Id of transaction to fetch all informations and notes from db
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: loading of all informations of the transaction selected 
          schema:
            $ref: '#/definitions/TransactionInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/transactions/transaction{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Details Module
      summary: Transaction's Additional Information
      description: API for fetching one user's transaction and all its info
      parameters:
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: integer
          name: id
          description: Id of transaction to fetch additionnal info from db
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: loading of all informations of the transaction selected 
          schema:
            $ref: '#/definitions/TransactionInformations'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    post:
      security:
        - Bearer: []
      tags:
        - Transaction Details Module
      summary: Adding Transaction's Additional Informations 
      description: API for adding transaction's additional informations
      parameters:
        - in: path
          type: integer
          name: id
          description: Id of transaction to fetch additionnal info from db
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: addtionnal informations for this transcation
          schema:
            $ref: '#/definitions/TransactionAdditionalInfos'
          required: true
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: Transaction additional informations created successully
          schema:
            $ref: '#/definitions/ApiResponseAdditionalInfos'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transaction Details Module
      summary: Editing Transaction's Additional Informations
      description: API for editing transaction's informations
      parameters:
        - in: path
          type: integer
          name: id
          description: Id of transaction to fetch additionnal info from db
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: addtionnal informations of transcation
          schema:
            $ref: '#/definitions/TransactionAdditionalInfos'
          required: true
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: Transaction's informations edited successfully
          schema:
            $ref: '#/definitions/ApiResponseAdditionalInfos'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Details Module
      summary: Deleting Transaction's Additional Informations 
      description: API for deleting Transaction's informations
      parameters:
        - in: path
          type: integer
          name: id
          description: Id of transaction to delete its info from db
          required: true
        - in: header
          type: 'string'
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        '200':
          description: Transaction informations deleted successfully
          schema:
            type: object
            properties:
              ApiResponse:
                $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':        
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: account balance after transaction
      

  TransactionInformations:
    type: object
    properties:
      transactionType:
        type: string
        description: transaction type
        enum: [Electronic, Card, Withdrowing, Debit, Other]
      category:
        type: string
        description: transaction category
        enum: [Food, Culture, Medical, Tech, Gardening, Fuel, Other]
      Notes:
        type: string
        description: various notes
      description:
        type: string
        description: transaction description
      amount:
        type: number
        description: transaction amount

  TransactionAdditionalInfos:
    type: object
    properties:
      transactionType:
        type: string
        description: transaction type
        enum: [Electronic, Card, Withdrowing, Debit, Other]
      category:
        type: string
        description: transaction category
        enum: [Food, Culture, Medical, Tech, Gardening, Fuel, Other]
      Notes:
        type: string
        description: various notes

  ApiResponseAdditionalInfos:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/TransactionAdditionalInfos'

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  